"""
models/menu_defaults.py — Configurações Padrão de Menu v3.0
"""

DEFAULT_MAIN_MENU = {
    "arquivo": {
        "label": "Arquivo",
        "ordem": 1,
        "items": [
            {"label": "Novo Projeto", "shortcut": "Ctrl+N", "action": "new_project"},
            {"label": "Abrir Projeto", "shortcut": "Ctrl+O", "action": "open_project"},
            {"separator": True},
            {"label": "Salvar", "shortcut": "Ctrl+S", "action": "save"},
            {"label": "Salvar Como...", "action": "save_as"},
            {"separator": True},
            {"label": "Exportar HTML", "action": "export_html"},
            {"label": "Exportar ZIP", "action": "export_zip"},
            {"separator": True},
            {"label": "Histórico de Versões", "action": "open_versions"},
            {"label": "Reset para Versão...", "action": "reset_version"},
            {"separator": True},
            {"label": "Sair", "shortcut": "Alt+F4", "action": "quit"},
        ],
    },
    "editar": {
        "label": "Editar",
        "ordem": 2,
        "items": [
            {"label": "Desfazer", "shortcut": "Ctrl+Z", "action": "undo"},
            {"label": "Refazer", "shortcut": "Ctrl+Y", "action": "redo"},
            {"separator": True},
            {"label": "Copiar", "shortcut": "Ctrl+C", "action": "copy"},
            {"label": "Colar", "shortcut": "Ctrl+V", "action": "paste"},
            {"label": "Recortar", "shortcut": "Ctrl+X", "action": "cut"},
            {"separator": True},
            {"label": "Duplicar", "shortcut": "Ctrl+D", "action": "duplicate"},
            {"label": "Excluir", "shortcut": "Del", "action": "delete"},
            {"separator": True},
            {"label": "Selecionar Todos", "shortcut": "Ctrl+A", "action": "select_all"},
        ],
    },
    "visualizar": {
        "label": "Visualizar",
        "ordem": 3,
        "items": [
            {"label": "Preview", "shortcut": "F5", "action": "preview"},
            {"separator": True},
            {"label": "Zoom +", "shortcut": "Ctrl++", "action": "zoom_in"},
            {"label": "Zoom -", "shortcut": "Ctrl+-", "action": "zoom_out"},
            {"label": "Zoom 100%", "shortcut": "Ctrl+0", "action": "zoom_reset"},
            {"separator": True},
            {"label": "Mostrar Grid", "type": "checkbox", "action": "toggle_grid"},
            {"label": "Mostrar Régua", "type": "checkbox", "action": "toggle_ruler"},
        ],
    },
    "inserir": {
        "label": "Inserir",
        "ordem": 4,
        "items": [
            {"label": "Botão", "action": "insert:button"},
            {"label": "Campo de Texto", "action": "insert:textbox"},
            {"label": "Textarea", "action": "insert:textarea"},
            {"label": "Combo", "action": "insert:combobox"},
            {"label": "CheckBox", "action": "insert:checkbox"},
            {"separator": True},
            {"label": "DataGrid", "action": "insert:datagrid"},
            {"label": "Chart", "action": "insert:chart"},
            {"separator": True},
            {"label": "Card", "action": "insert:card"},
            {"label": "Painel", "action": "insert:panel"},
            {"label": "Abas (Tabs)", "action": "insert:tabs"},
            {"separator": True},
            {"label": "Imagem", "action": "insert:image"},
            {"label": "Ícone", "action": "insert:icon"},
            {"label": "Progress Bar", "action": "insert:progressbar"},
        ],
    },
    "ferramentas": {
        "label": "Ferramentas",
        "ordem": 5,
        "items": [
            {"label": "Editor de Eventos", "action": "open_events"},
            {"label": "Editor de Regras", "action": "open_rules"},
            {"label": "Gerenciador OData", "action": "open_odata"},
            {"separator": True},
            {"label": "Gerador de Código", "action": "generate_code"},
            {"label": "Editor de Menu (DS_MENU)", "action": "tx:DS_MENU"},
            {"label": "Build & Deploy (DS_BUILD)", "action": "tx:DS_BUILD"},
        ],
    },
    "ajuda": {
        "label": "Ajuda",
        "ordem": 6,
        "items": [
            {"label": "Documentação", "shortcut": "F1", "action": "open_docs"},
            {"label": "Transações", "action": "tx:DS_HOME"},
            {"label": "Sobre", "action": "about"},
        ],
    },
}

DEFAULT_SIDEBAR = {
    "sections": [
        {
            "id": "pages",
            "icon": "bi-files",
            "label": "Páginas",
            "order": 1,
            "expanded": True,
            "type": "pages_tree",
        },
        {
            "id": "components",
            "icon": "bi-grid-3x3-gap",
            "label": "Componentes",
            "order": 2,
            "expanded": True,
            "type": "component_palette",
        },
        {
            "id": "outline",
            "icon": "bi-list-nested",
            "label": "Outline",
            "order": 3,
            "expanded": False,
            "type": "outline_tree",
        },
        {
            "id": "odata",
            "icon": "bi-cloud-arrow-down",
            "label": "OData",
            "order": 4,
            "expanded": False,
            "type": "odata_panel",
        },
        {
            "id": "history",
            "icon": "bi-clock-history",
            "label": "Histórico",
            "order": 5,
            "expanded": False,
            "type": "version_panel",
        },
    ]
}
